[settings]
timeout = 1000
bootnode = true

[relaychain.genesis.runtime.runtime_genesis_config.configuration.config]
  max_validators_per_core = 1
  needed_approvals = 2
  max_validators = 1000

[relaychain]
chain = "rococo-local"
chain_spec_command = "../polkadot/target/testnet/polkadot build-spec --chain rococo-local"
default_command = "../polkadot/target/testnet/polkadot"

  [[relaychain.node_groups]]
  name = "honest"
  command = "../polkadot/target/testnet/polkadot -lparachain=trace"
  count = 3

  [[relaychain.node_groups]]
  name = "malus-garbage-suggester"
  command = "../polkadot/target/testnet/malus suggest-garbage-candidate -lparachain=trace"
  count = 1

  # [[relaychain.node_groups]]
  # name = "malus-disputer"
  # command = "../polkadot/target/testnet/malus dispute-ancestor -lparachain=debug"
  # count = 2
 
{% for id in range(2000,2001) %}
[[parachains]]
id = {{id}}
addToGenesis = true
genesis_state_generator = "../polkadot/target/testnet/undying-collator export-genesis-state --pov-size=20000 --pvf-complexity=2"
    [parachains.collator]
    name = "collator"
    command = "../polkadot/target/testnet/undying-collator"
    args = ["-lparachain=debug", "--pov-size=20000", "--parachain-id={{id}}", "--pvf-complexity=2"]

{% endfor %}

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
