[package]
name = "xcm-simulator-fuzzer"
description = "Examples of xcm-simulator usage."
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
honggfuzz = "0.5.55"
scale-info = { version = "2.1.2", features = ["derive"] }

frame-system = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "oty-optional-pov-limit" }

xcm = { path = "../../" }
xcm-simulator = { path = "../" }
xcm-executor = { path = "../../xcm-executor" }
xcm-builder = { path = "../../xcm-builder" }
pallet-xcm = { path = "../../pallet-xcm" }
polkadot-core-primitives = { path = "../../../core-primitives" }
polkadot-runtime-parachains = { path = "../../../runtime/parachains" }
polkadot-parachain = { path = "../../../parachain" }

[features]
runtime-benchmarks = [
    "pallet-xcm/runtime-benchmarks",
]

[[bin]]
path = "src/fuzz.rs"
name = "xcm-fuzzer"
