[package]
name = "polkadot-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server"] }
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
txpool-api = { package = "sc-transaction-pool-api", git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
beefy-gadget = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
beefy-gadget-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
substrate-state-trie-migration-rpc = { git = "https://github.com/paritytech/substrate", branch = "bkchr-speed-up-kademlia" }
