[package]
name = "polkadot-rpc"
version = "0.9.32"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server"] }
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
txpool-api = { package = "sc-transaction-pool-api", git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
beefy-gadget = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
beefy-gadget-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
substrate-state-trie-migration-rpc = { git = "https://github.com/paritytech/substrate", branch = "at/substrate" }
