[package]
name = "polkadot-node-events"
version = "0.9.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../gum" }
polkadot-node-subsystem = {path = "../subsystem" }
sc-utils = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
jsonrpsee = { version = "0.15.1", features = ["server"] }
thiserror = "1.0.31"
serde = { version = "1.0.137", features = ["derive"] }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
maplit = "1.0.2"
parity-scale-codec = "3.1.5"
polkadot-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
