[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.18"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
polkadot-primitives = { path = "../" }
