[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.16"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "kiz-inner-hashing-test" }
sp-application-crypto = { package = "sp-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false , branch = "kiz-inner-hashing-test" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "kiz-inner-hashing-test" }
polkadot-primitives = { path = "../" }
