[package]
name = "remote-ext-tests-bags-list"
version = "0.9.18"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
polkadot-runtime = { version = "0.9.18", path = "../../../runtime/polkadot" }
kusama-runtime = { version = "0.9.18", path = "../../../runtime/kusama" }
westend-runtime = { version = "0.9.18", path = "../../../runtime/westend" }
polkadot-runtime-constants = { version = "0.9.18", path = "../../../runtime/polkadot/constants" }
kusama-runtime-constants = { version = "0.9.18", path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { version = "0.9.18", path = "../../../runtime/westend/constants" }

pallet-bags-list-remote-tests = { git = "https://github.com/paritytech/substrate", branch = "sandreim/task_idle_metric" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "sandreim/task_idle_metric" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "sandreim/task_idle_metric" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "sandreim/task_idle_metric" }

clap = { version = "3.1", features = ["derive"] }
log = "0.4.14"
tokio = { version = "1.17.0", features = ["macros"] }
