[package]
name = "polkadot-node-metrics"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Subsystem traits and message definitions"

[dependencies]
futures = "0.3.17"
futures-timer = "3.0.2"

metered-channel = { path = "../metered-channel" }

substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", rev = "5714e30cd280906a8f20e699b187fdef22989ffc" }

[features]
default = []
