[package]
name = "polkadot-node-metrics"
description = "Subsystem metric helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../gum" }

metered = { package = "prioritized-metered-channel", version = "0.2.0" }

# Both `sc-service` and `sc-cli` are required by runtime metrics `logger_hook()`.
sc-service = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }

substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
codec = { package = "parity-scale-codec", version = "3.4.0" }
primitives = { package = "polkadot-primitives", path = "../../primitives/" }
bs58 = { version = "0.4.0", features = ["alloc"] }
log = "0.4.17"

[dev-dependencies]
assert_cmd = "2.0.4"
tempfile = "3.2.0"
hyper = { version = "0.14.20", default-features = false, features = ["http1", "tcp"] }
tokio = "1.24.2"
polkadot-test-service = { path = "../test/service", features=["runtime-metrics"]}
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "sync-evict-idle-peers" }
prometheus-parse = {version = "0.2.2"}

[features]
default = []
runtime-metrics = []
runtime-benchmarks = []
