[package]
name = "polkadot-node-core-runtime-api"
version = "0.9.9"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.17"
tracing = "0.1.26"
memory-lru = "0.1.0"
parity-util-mem = { version = "0.10.0", default-features = false }

sp-api = { git = "https://github.com/paritytech/substrate", branch = "grandpa_finality_logs" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "grandpa_finality_logs" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "grandpa_finality_logs" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "grandpa_finality_logs" }

polkadot-primitives = { path = "../../../primitives" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "grandpa_finality_logs" }
futures = { version = "0.3.17", features = ["thread-pool"] }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-node-primitives = { path = "../../primitives" }
