[package]
name = "millau-bridge-node"
description = "Substrate node compatible with Millau runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
jsonrpc-core = "18.0"
structopt = "0.3.21"
serde_json = "1.0.59"

# Bridge dependencies

bp-millau = { path = "../../../primitives/chain-millau" }
bp-runtime = { path = "../../../primitives/runtime" }
millau-runtime = { path = "../runtime" }
pallet-bridge-messages = { path = "../../../modules/messages" }

# Substrate Dependencies

beefy-gadget = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
beefy-gadget-rpc = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
beefy-primitives = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
node-inspect = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update", features = ["wasmtime"] }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "shawntabrizi-bounty-deposit-update" }

[features]
default = []
runtime-benchmarks = [
	"millau-runtime/runtime-benchmarks",
]
